package dao;

import java.util.List;
import model.DirectoryInformation;
import model.DirectoryInformationExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DirectoryInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    long countByExample(DirectoryInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    int deleteByExample(DirectoryInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    int deleteByPrimaryKey(Integer directoryInformationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    int insert(DirectoryInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    int insertSelective(DirectoryInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    List<DirectoryInformation> selectByExample(DirectoryInformationExample example);
    
    /**
     * Select all rows
     */
    List<DirectoryInformation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    DirectoryInformation selectByPrimaryKey(Integer directoryInformationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    int updateByExampleSelective(@Param("record") DirectoryInformation record, @Param("example") DirectoryInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    int updateByExample(@Param("record") DirectoryInformation record, @Param("example") DirectoryInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    int updateByPrimaryKeySelective(DirectoryInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory_information
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    int updateByPrimaryKey(DirectoryInformation record);
}