package model;

public class DirectoryInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.DIRECTORY_INFORMATION_ID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer directoryInformationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.UNITID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer unitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.INSTNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String instnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.ADDR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CITY
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.STABBR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String stabbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.ZIP
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.FIPS
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String fips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.OBEREG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String obereg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CHFNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String chfnm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CHFTITLE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String chftitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.GENTELE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String gentele;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.EIN
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String ein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.OPEID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String opeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.OPEFLAG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String opeflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.WEBADDR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String webaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.ADMINURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String adminurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.FAIDURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String faidurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.APPLURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String applurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.NPRICURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String npricurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.SECTOR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String sector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.ICLEVEL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String iclevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CONTROL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String control;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.HLOFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer hloffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.UGOFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer ugoffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.GROFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer groffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.HDEGOFR1
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer hdegofr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.DEGGRANT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer deggrant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.HBCU
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String hbcu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.HOSPITAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String hospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.MEDICAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String medical;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.TRIBAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String tribal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.LOCALE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String locale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.OPENPUBL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String openpubl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.ACT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String act;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.NEWID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String newid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.DEATHYR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String deathyr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CLOSEDAT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String closedat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CYACTIVE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String cyactive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.POSTSEC
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String postsec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.PSEFLAG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String pseflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.PSET4FLG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String pset4flg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.RPTMTH
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String rptmth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.IALIAS
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String ialias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.INSTCAT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String instcat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CCBASIC
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String ccbasic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CCIPUG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String ccipug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CCIPGRAD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String ccipgrad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CCUGPROF
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String ccugprof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CCENRPRF
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String ccenrprf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CCSIZSET
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String ccsizset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CARNEGIE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String carnegie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.LANDGRNT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String landgrnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.INSTSIZE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String instsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CBSA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String cbsa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CBSATYPE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String cbsatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CSA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String csa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.NECTA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String necta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.F1SYSTYP
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String f1systyp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.F1SYSNAM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String f1sysnam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.FAXTELE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String faxtele;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.COUNTYCD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String countycd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.COUNTYNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String countynm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.CNGDSTCD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String cngdstcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.LONGITUD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String longitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.LATITUDE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.YEAR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory_information.ACTIVE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    private Integer active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.DIRECTORY_INFORMATION_ID
     *
     * @return the value of directory_information.DIRECTORY_INFORMATION_ID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getDirectoryInformationId() {
        return directoryInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.DIRECTORY_INFORMATION_ID
     *
     * @param directoryInformationId the value for directory_information.DIRECTORY_INFORMATION_ID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setDirectoryInformationId(Integer directoryInformationId) {
        this.directoryInformationId = directoryInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.UNITID
     *
     * @return the value of directory_information.UNITID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.UNITID
     *
     * @param unitid the value for directory_information.UNITID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.INSTNM
     *
     * @return the value of directory_information.INSTNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getInstnm() {
        return instnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.INSTNM
     *
     * @param instnm the value for directory_information.INSTNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setInstnm(String instnm) {
        this.instnm = instnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.ADDR
     *
     * @return the value of directory_information.ADDR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.ADDR
     *
     * @param addr the value for directory_information.ADDR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CITY
     *
     * @return the value of directory_information.CITY
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CITY
     *
     * @param city the value for directory_information.CITY
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.STABBR
     *
     * @return the value of directory_information.STABBR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getStabbr() {
        return stabbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.STABBR
     *
     * @param stabbr the value for directory_information.STABBR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setStabbr(String stabbr) {
        this.stabbr = stabbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.ZIP
     *
     * @return the value of directory_information.ZIP
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.ZIP
     *
     * @param zip the value for directory_information.ZIP
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.FIPS
     *
     * @return the value of directory_information.FIPS
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getFips() {
        return fips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.FIPS
     *
     * @param fips the value for directory_information.FIPS
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setFips(String fips) {
        this.fips = fips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.OBEREG
     *
     * @return the value of directory_information.OBEREG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getObereg() {
        return obereg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.OBEREG
     *
     * @param obereg the value for directory_information.OBEREG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setObereg(String obereg) {
        this.obereg = obereg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CHFNM
     *
     * @return the value of directory_information.CHFNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getChfnm() {
        return chfnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CHFNM
     *
     * @param chfnm the value for directory_information.CHFNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setChfnm(String chfnm) {
        this.chfnm = chfnm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CHFTITLE
     *
     * @return the value of directory_information.CHFTITLE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getChftitle() {
        return chftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CHFTITLE
     *
     * @param chftitle the value for directory_information.CHFTITLE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setChftitle(String chftitle) {
        this.chftitle = chftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.GENTELE
     *
     * @return the value of directory_information.GENTELE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getGentele() {
        return gentele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.GENTELE
     *
     * @param gentele the value for directory_information.GENTELE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setGentele(String gentele) {
        this.gentele = gentele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.EIN
     *
     * @return the value of directory_information.EIN
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getEin() {
        return ein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.EIN
     *
     * @param ein the value for directory_information.EIN
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setEin(String ein) {
        this.ein = ein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.OPEID
     *
     * @return the value of directory_information.OPEID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getOpeid() {
        return opeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.OPEID
     *
     * @param opeid the value for directory_information.OPEID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setOpeid(String opeid) {
        this.opeid = opeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.OPEFLAG
     *
     * @return the value of directory_information.OPEFLAG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getOpeflag() {
        return opeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.OPEFLAG
     *
     * @param opeflag the value for directory_information.OPEFLAG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setOpeflag(String opeflag) {
        this.opeflag = opeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.WEBADDR
     *
     * @return the value of directory_information.WEBADDR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getWebaddr() {
        return webaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.WEBADDR
     *
     * @param webaddr the value for directory_information.WEBADDR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setWebaddr(String webaddr) {
        this.webaddr = webaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.ADMINURL
     *
     * @return the value of directory_information.ADMINURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getAdminurl() {
        return adminurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.ADMINURL
     *
     * @param adminurl the value for directory_information.ADMINURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setAdminurl(String adminurl) {
        this.adminurl = adminurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.FAIDURL
     *
     * @return the value of directory_information.FAIDURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getFaidurl() {
        return faidurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.FAIDURL
     *
     * @param faidurl the value for directory_information.FAIDURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setFaidurl(String faidurl) {
        this.faidurl = faidurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.APPLURL
     *
     * @return the value of directory_information.APPLURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getApplurl() {
        return applurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.APPLURL
     *
     * @param applurl the value for directory_information.APPLURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setApplurl(String applurl) {
        this.applurl = applurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.NPRICURL
     *
     * @return the value of directory_information.NPRICURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getNpricurl() {
        return npricurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.NPRICURL
     *
     * @param npricurl the value for directory_information.NPRICURL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setNpricurl(String npricurl) {
        this.npricurl = npricurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.SECTOR
     *
     * @return the value of directory_information.SECTOR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getSector() {
        return sector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.SECTOR
     *
     * @param sector the value for directory_information.SECTOR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setSector(String sector) {
        this.sector = sector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.ICLEVEL
     *
     * @return the value of directory_information.ICLEVEL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getIclevel() {
        return iclevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.ICLEVEL
     *
     * @param iclevel the value for directory_information.ICLEVEL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setIclevel(String iclevel) {
        this.iclevel = iclevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CONTROL
     *
     * @return the value of directory_information.CONTROL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getControl() {
        return control;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CONTROL
     *
     * @param control the value for directory_information.CONTROL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setControl(String control) {
        this.control = control;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.HLOFFER
     *
     * @return the value of directory_information.HLOFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getHloffer() {
        return hloffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.HLOFFER
     *
     * @param hloffer the value for directory_information.HLOFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setHloffer(Integer hloffer) {
        this.hloffer = hloffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.UGOFFER
     *
     * @return the value of directory_information.UGOFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getUgoffer() {
        return ugoffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.UGOFFER
     *
     * @param ugoffer the value for directory_information.UGOFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setUgoffer(Integer ugoffer) {
        this.ugoffer = ugoffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.GROFFER
     *
     * @return the value of directory_information.GROFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getGroffer() {
        return groffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.GROFFER
     *
     * @param groffer the value for directory_information.GROFFER
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setGroffer(Integer groffer) {
        this.groffer = groffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.HDEGOFR1
     *
     * @return the value of directory_information.HDEGOFR1
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getHdegofr1() {
        return hdegofr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.HDEGOFR1
     *
     * @param hdegofr1 the value for directory_information.HDEGOFR1
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setHdegofr1(Integer hdegofr1) {
        this.hdegofr1 = hdegofr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.DEGGRANT
     *
     * @return the value of directory_information.DEGGRANT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getDeggrant() {
        return deggrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.DEGGRANT
     *
     * @param deggrant the value for directory_information.DEGGRANT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setDeggrant(Integer deggrant) {
        this.deggrant = deggrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.HBCU
     *
     * @return the value of directory_information.HBCU
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getHbcu() {
        return hbcu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.HBCU
     *
     * @param hbcu the value for directory_information.HBCU
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setHbcu(String hbcu) {
        this.hbcu = hbcu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.HOSPITAL
     *
     * @return the value of directory_information.HOSPITAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.HOSPITAL
     *
     * @param hospital the value for directory_information.HOSPITAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setHospital(String hospital) {
        this.hospital = hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.MEDICAL
     *
     * @return the value of directory_information.MEDICAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getMedical() {
        return medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.MEDICAL
     *
     * @param medical the value for directory_information.MEDICAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setMedical(String medical) {
        this.medical = medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.TRIBAL
     *
     * @return the value of directory_information.TRIBAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getTribal() {
        return tribal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.TRIBAL
     *
     * @param tribal the value for directory_information.TRIBAL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setTribal(String tribal) {
        this.tribal = tribal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.LOCALE
     *
     * @return the value of directory_information.LOCALE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getLocale() {
        return locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.LOCALE
     *
     * @param locale the value for directory_information.LOCALE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setLocale(String locale) {
        this.locale = locale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.OPENPUBL
     *
     * @return the value of directory_information.OPENPUBL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getOpenpubl() {
        return openpubl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.OPENPUBL
     *
     * @param openpubl the value for directory_information.OPENPUBL
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setOpenpubl(String openpubl) {
        this.openpubl = openpubl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.ACT
     *
     * @return the value of directory_information.ACT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getAct() {
        return act;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.ACT
     *
     * @param act the value for directory_information.ACT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setAct(String act) {
        this.act = act;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.NEWID
     *
     * @return the value of directory_information.NEWID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getNewid() {
        return newid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.NEWID
     *
     * @param newid the value for directory_information.NEWID
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setNewid(String newid) {
        this.newid = newid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.DEATHYR
     *
     * @return the value of directory_information.DEATHYR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getDeathyr() {
        return deathyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.DEATHYR
     *
     * @param deathyr the value for directory_information.DEATHYR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setDeathyr(String deathyr) {
        this.deathyr = deathyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CLOSEDAT
     *
     * @return the value of directory_information.CLOSEDAT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getClosedat() {
        return closedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CLOSEDAT
     *
     * @param closedat the value for directory_information.CLOSEDAT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setClosedat(String closedat) {
        this.closedat = closedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CYACTIVE
     *
     * @return the value of directory_information.CYACTIVE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCyactive() {
        return cyactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CYACTIVE
     *
     * @param cyactive the value for directory_information.CYACTIVE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCyactive(String cyactive) {
        this.cyactive = cyactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.POSTSEC
     *
     * @return the value of directory_information.POSTSEC
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getPostsec() {
        return postsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.POSTSEC
     *
     * @param postsec the value for directory_information.POSTSEC
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setPostsec(String postsec) {
        this.postsec = postsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.PSEFLAG
     *
     * @return the value of directory_information.PSEFLAG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getPseflag() {
        return pseflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.PSEFLAG
     *
     * @param pseflag the value for directory_information.PSEFLAG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setPseflag(String pseflag) {
        this.pseflag = pseflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.PSET4FLG
     *
     * @return the value of directory_information.PSET4FLG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getPset4flg() {
        return pset4flg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.PSET4FLG
     *
     * @param pset4flg the value for directory_information.PSET4FLG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setPset4flg(String pset4flg) {
        this.pset4flg = pset4flg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.RPTMTH
     *
     * @return the value of directory_information.RPTMTH
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getRptmth() {
        return rptmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.RPTMTH
     *
     * @param rptmth the value for directory_information.RPTMTH
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setRptmth(String rptmth) {
        this.rptmth = rptmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.IALIAS
     *
     * @return the value of directory_information.IALIAS
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getIalias() {
        return ialias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.IALIAS
     *
     * @param ialias the value for directory_information.IALIAS
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setIalias(String ialias) {
        this.ialias = ialias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.INSTCAT
     *
     * @return the value of directory_information.INSTCAT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getInstcat() {
        return instcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.INSTCAT
     *
     * @param instcat the value for directory_information.INSTCAT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setInstcat(String instcat) {
        this.instcat = instcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CCBASIC
     *
     * @return the value of directory_information.CCBASIC
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCcbasic() {
        return ccbasic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CCBASIC
     *
     * @param ccbasic the value for directory_information.CCBASIC
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCcbasic(String ccbasic) {
        this.ccbasic = ccbasic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CCIPUG
     *
     * @return the value of directory_information.CCIPUG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCcipug() {
        return ccipug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CCIPUG
     *
     * @param ccipug the value for directory_information.CCIPUG
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCcipug(String ccipug) {
        this.ccipug = ccipug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CCIPGRAD
     *
     * @return the value of directory_information.CCIPGRAD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCcipgrad() {
        return ccipgrad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CCIPGRAD
     *
     * @param ccipgrad the value for directory_information.CCIPGRAD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCcipgrad(String ccipgrad) {
        this.ccipgrad = ccipgrad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CCUGPROF
     *
     * @return the value of directory_information.CCUGPROF
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCcugprof() {
        return ccugprof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CCUGPROF
     *
     * @param ccugprof the value for directory_information.CCUGPROF
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCcugprof(String ccugprof) {
        this.ccugprof = ccugprof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CCENRPRF
     *
     * @return the value of directory_information.CCENRPRF
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCcenrprf() {
        return ccenrprf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CCENRPRF
     *
     * @param ccenrprf the value for directory_information.CCENRPRF
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCcenrprf(String ccenrprf) {
        this.ccenrprf = ccenrprf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CCSIZSET
     *
     * @return the value of directory_information.CCSIZSET
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCcsizset() {
        return ccsizset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CCSIZSET
     *
     * @param ccsizset the value for directory_information.CCSIZSET
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCcsizset(String ccsizset) {
        this.ccsizset = ccsizset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CARNEGIE
     *
     * @return the value of directory_information.CARNEGIE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCarnegie() {
        return carnegie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CARNEGIE
     *
     * @param carnegie the value for directory_information.CARNEGIE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCarnegie(String carnegie) {
        this.carnegie = carnegie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.LANDGRNT
     *
     * @return the value of directory_information.LANDGRNT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getLandgrnt() {
        return landgrnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.LANDGRNT
     *
     * @param landgrnt the value for directory_information.LANDGRNT
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setLandgrnt(String landgrnt) {
        this.landgrnt = landgrnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.INSTSIZE
     *
     * @return the value of directory_information.INSTSIZE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getInstsize() {
        return instsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.INSTSIZE
     *
     * @param instsize the value for directory_information.INSTSIZE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setInstsize(String instsize) {
        this.instsize = instsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CBSA
     *
     * @return the value of directory_information.CBSA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCbsa() {
        return cbsa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CBSA
     *
     * @param cbsa the value for directory_information.CBSA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCbsa(String cbsa) {
        this.cbsa = cbsa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CBSATYPE
     *
     * @return the value of directory_information.CBSATYPE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCbsatype() {
        return cbsatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CBSATYPE
     *
     * @param cbsatype the value for directory_information.CBSATYPE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCbsatype(String cbsatype) {
        this.cbsatype = cbsatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CSA
     *
     * @return the value of directory_information.CSA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCsa() {
        return csa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CSA
     *
     * @param csa the value for directory_information.CSA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCsa(String csa) {
        this.csa = csa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.NECTA
     *
     * @return the value of directory_information.NECTA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getNecta() {
        return necta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.NECTA
     *
     * @param necta the value for directory_information.NECTA
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setNecta(String necta) {
        this.necta = necta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.F1SYSTYP
     *
     * @return the value of directory_information.F1SYSTYP
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getF1systyp() {
        return f1systyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.F1SYSTYP
     *
     * @param f1systyp the value for directory_information.F1SYSTYP
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setF1systyp(String f1systyp) {
        this.f1systyp = f1systyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.F1SYSNAM
     *
     * @return the value of directory_information.F1SYSNAM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getF1sysnam() {
        return f1sysnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.F1SYSNAM
     *
     * @param f1sysnam the value for directory_information.F1SYSNAM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setF1sysnam(String f1sysnam) {
        this.f1sysnam = f1sysnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.FAXTELE
     *
     * @return the value of directory_information.FAXTELE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getFaxtele() {
        return faxtele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.FAXTELE
     *
     * @param faxtele the value for directory_information.FAXTELE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setFaxtele(String faxtele) {
        this.faxtele = faxtele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.COUNTYCD
     *
     * @return the value of directory_information.COUNTYCD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCountycd() {
        return countycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.COUNTYCD
     *
     * @param countycd the value for directory_information.COUNTYCD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCountycd(String countycd) {
        this.countycd = countycd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.COUNTYNM
     *
     * @return the value of directory_information.COUNTYNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCountynm() {
        return countynm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.COUNTYNM
     *
     * @param countynm the value for directory_information.COUNTYNM
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCountynm(String countynm) {
        this.countynm = countynm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.CNGDSTCD
     *
     * @return the value of directory_information.CNGDSTCD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getCngdstcd() {
        return cngdstcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.CNGDSTCD
     *
     * @param cngdstcd the value for directory_information.CNGDSTCD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setCngdstcd(String cngdstcd) {
        this.cngdstcd = cngdstcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.LONGITUD
     *
     * @return the value of directory_information.LONGITUD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getLongitud() {
        return longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.LONGITUD
     *
     * @param longitud the value for directory_information.LONGITUD
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.LATITUDE
     *
     * @return the value of directory_information.LATITUDE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.LATITUDE
     *
     * @param latitude the value for directory_information.LATITUDE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.YEAR
     *
     * @return the value of directory_information.YEAR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.YEAR
     *
     * @param year the value for directory_information.YEAR
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory_information.ACTIVE
     *
     * @return the value of directory_information.ACTIVE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory_information.ACTIVE
     *
     * @param active the value for directory_information.ACTIVE
     *
     * @mbg.generated Fri Sep 30 12:10:36 CEST 2016
     */
    public void setActive(Integer active) {
        this.active = active;
    }
}